[project]
name = "e2e-ai-agent-health-fitness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agno>=1.1.4",
    "huggingface-hub>=0.28.1",
    "python-dotenv>=1.0.1",
    "ruff>=0.9.6",
    "streamlit>=1.42.1",
]
